# -*- coding: utf-8 -*-
"""v1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14c4lPid_eMWKdwxbkAMlUhmyna1tnHiY
"""



a = float(input("Enter the value for a: "))
b = float(input("Enter the value for b: "))
c = float(input("Enter the value for c: "))
x = float(input("Enter the value for x: "))

# Calculating the value of y
y = a * x * x + b * x + c
print(y)